apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-service.monitoring.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: pxc-mysql
        static_configs:
          - targets:
              - localhost
            labels:
              job: pxc-mysql
              __path__: /var/lib/mysql/*.log

      - job_name: proxysql
        static_configs:
          - targets:
              - localhost
            labels:
              job: proxysql
              __path__: /var/lib/proxysql/*.log
