apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-service.monitoring.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      # mysql-operator 네임스페이스 로그 - 실제 파일 구조 반영
      - job_name: mysql-operator-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: mysql-operator
              namespace: mysql-operator
              __path__: /var/log/pods/mysql-operator_*/*/*.log
        pipeline_stages:
          - cri: {}
          - regex:
              expression: '^/var/log/pods/mysql-operator_(?P<pod_name>[^_]+).*?/(?P<container_name>[^/]+)/.*$'
          - labels:
              pod_name:
              container_name:

      # web-service 네임스페이스 로그
      - job_name: web-service-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: web-service
              namespace: web-service
              __path__: /var/log/pods/web-service_*/*/*.log
        pipeline_stages:
          - cri: {}
          - regex:
              expression: '^/var/log/pods/web-service_(?P<pod_name>[^_]+).*?/(?P<container_name>[^/]+)/.*$'
          - labels:
              pod_name:
              container_name:
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
    spec:
      serviceAccountName: promtail
      containers:
        - name: promtail
          image: grafana/promtail:2.9.1
          args:
            - -config.file=/etc/promtail/promtail-config.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: pods
              mountPath: /var/log/pods
              readOnly: true
            - name: containers
              mountPath: /var/log/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: pods
          hostPath:
            path: /var/log/pods
            type: Directory
        - name: containers
          hostPath:
            path: /var/log/containers
            type: Directory
