apiVersion: v1
kind: Pod
metadata:
  name: mysql-with-promtail
  namespace: mysql-operator
  labels:
    app: mysql
spec:
  containers:
  - name: promtail
    image: grafana/promtail:2.8.2
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    args:
      - -config.file=/etc/promtail/config.yaml
    volumeMounts:
      - name: mysql-logs
        mountPath: /var/log/mysql
      - name: promtail-config
        mountPath: /etc/promtail
  volumes:
  - name: mysql-logs
    emptyDir: {}
  - name: promtail-config
    configMap:
      name: promtail-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: mysql-operator
data:
  config.yaml: |
    server:
      http_listen_port: 9080

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-service.monitoring.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: mysql-general-log
        static_configs:
          - targets:
              - localhost
            labels:
              job: mysql
              __path__: /var/log/mysql/mysql-general.log
