# operator.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: mysql-operator
  labels:
    app: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      containers:
        - name: mysql-operator
          image: ghcr.io/bitpoke/mysql-operator:0.4.0
          imagePullPolicy: Always
---
# CRDs 설치 (선택: 별도 yaml로 분리 가능)
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
# ... MySQLCluster 등 필요한 CRD들
