apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
spec:
  destination:
    namespace: mysql-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: mysql-operator
    helm:
      parameters:
        - name: replicaCount
          value: "3"
    repoURL: https://helm-charts.bitpoke.io
    targetRevision: 0.6.3
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true