# apiVersion: v1
# kind: Service
# metadata:
#   name: dummy-service
#   namespace: default
# spec:
#   selector:
#     app: dummy
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: dummy
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: dummy
#   template:
#     metadata:
#       labels:
#         app: dummy
#     spec:
#       containers:
#         - name: dummy
#           image: nginx
#           ports:
#             - containerPort: 80
#           resources:
#             requests:
#               memory: "64Mi"
#               cpu: "50m"
#             limits:
#               memory: "128Mi"
#               cpu: "100m"
