apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  namespace: monitoring
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: loki
        image: grafana/loki:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        args: 
        - "-config.file=/etc/loki/loki.yaml"
        ports:
        - name: loki 
          containerPort: 3100
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki
        - name: loki-data
          mountPath: /loki
      volumes:
      - name: loki-config
        configMap:
          name: loki-configmap
          items:
          - key: loki.yaml
            path: loki.yaml
      - name: loki-data 
        persistentVolumeClaim:
          claimName: loki-data-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-configmap
  namespace: monitoring
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      path_prefix: /loki
      replication_factor: 1
      storage:
        s3:
          endpoint: minio-service:9000
          s3forcepathstyle: true
          bucketnames: loki
          access_key_id: minio_access_key
          secret_access_key: minio_secret_key
          insecure: true
      ring:
        kvstore:
          store: inmemory
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h
---
apiVersion: v1 
kind: Service 
metadata: 
  name: loki-service 
  namespace: monitoring
  labels: 
    app: loki
spec: 
  selector: 
    app: loki 
  ports: 
    - port: 3100 
      targetPort: 3100
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-data-pv
  namespace: monitoring
  labels:
    app: loki-data-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/f/dev/data/loki-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data-pvc
  namespace: monitoring
spec:
  volumeName: loki-data-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
출처: https://luvstudy.tistory.com/238 [파란하늘의 지식창고:티스토리]