apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  namespace: monitoring
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: loki
        image: grafana/loki:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        args: 
        - "-config.file=/etc/loki/loki.yaml"
        ports:
        - name: loki 
          containerPort: 3100
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki
        - name: loki-data
          mountPath: /loki
      volumes:
      - name: loki-config
        configMap:
          name: loki-configmap
          items:
          - key: loki.yaml
            path: loki.yaml
      - name: loki-data 
        persistentVolumeClaim:
          claimName: loki-data-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-configmap
  namespace: monitoring
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      max_chunk_age: 1h
      chunk_target_size: 1048576
      chunk_retain_period: 30s
      wal:
        enabled: true
        dir: /loki/wal

    limits_config:
      ingestion_rate_mb: 4
      ingestion_burst_size_mb: 6
      max_streams_per_user: 0

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks

    compactor:
      working_directory: /loki/compactor
      compaction_interval: 5m

    query_range:
      parallelise_shardable_queries: true
      cache_results: true

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true

    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
---
apiVersion: v1 
kind: Service 
metadata: 
  name: loki-service 
  namespace: monitoring
  labels: 
    app: loki
spec: 
  selector: 
    app: loki 
  ports: 
    - port: 3100 
      targetPort: 3100
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-data-pv
  labels:
    app: loki-data-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/f/dev/data/loki-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data-pvc
  namespace: monitoring
spec:
  volumeName: loki-data-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
