apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hskang@neteer.co.kr
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-service-ingress
  namespace: web-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"   # cert-manager 사용
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: nkp.neteer.co.kr     # 도메인
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service-nkp   # ArgoCD의 서비스 이름
            port:
              number: 443         # 서비스의 HTTPS 포트
  tls:
  - hosts:
    - nkp.neteer.co.kr
    secretName: web-service-tls # cert-manager가 생성할 Secret
