apiVersion: v1
kind: Namespace
metadata:
  name: web-service
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: web-service
  type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "{{ .Values.imagePullSecrets.ghcr.auth }}"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service-nkp
  namespace: web-service
  labels:
    app: web-service-nkp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-service-nkp
  template:
    metadata:
      labels:
        app: web-service-nkp
    spec:
      containers:
        - name: web-service-nkp
          image: ghcr.io/neteer-cs-biz/web-service-nkp:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: REAL_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: web-service-config
                  key: REAL_HOSTNAME
      imagePullSecrets:
        - name: ghcr-secret
          
---
apiVersion: v1
kind: Service
metadata:
  name: web-service-nkp
  namespace: web-service
spec:
  selector:
    app: web-service-nkp
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-service-config
  namespace: web-service
data:
  REAL_HOSTNAME: "nkp.neteer.co.kr"  # 실제 호스트명으로 변경
