apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  spec:
    template:
      spec:
        containers:
        - name: nginx-ingress-controller
          args:
            - /nginx-ingress-controller
            - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
          ports:
          - containerPort: 3306
            name: mysql-tcp
          - containerPort: 6032
            name: postgres-tcp