apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  "3306": "mysql-operator/my-cluster-proxysql:3306"
  "6032": "mysql-operator/my-cluster-proxysql:6032"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress-controller
  template:
    metadata:
      labels:
        app: nginx-ingress-controller
    spec:
      containers:
      - name: nginx-ingress-controller
        image: registry.k8s.io/ingress-nginx/controller:v1.8.1
        args:
          - /nginx-ingress-controller
          - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 3306
          name: mysql-tcp
        - containerPort: 6032
          name: proxysql-admin-tcp
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-service
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - name: mysql-tcp
    port: 3306
    targetPort: 3306
    nodePort: 30306
  - name: proxysql-admin-tcp
    port: 6032
    targetPort: 6032
    nodePort: 30632
  selector:
    app: nginx-ingress-controller