apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: my-cluster
  namespace: mysql-operator
spec:
  crVersion: 1.11.0
  secretsName: my-cluster-secret
  sslSecretName: my-cluster-ssl
  sslInternalSecretName: my-cluster-ssl-internal

  mysqlVersion: 8.0.35-27.1

  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.35-27.1
    configuration: |
      [mysqld]
      log_error=/proc/self/fd/2
      general_log=1
      general_log_file=/proc/self/fd/1
      log_bin_trust_function_creators=1
    podSpec:
      securityContext:
        runAsUser: 1001   # MySQL 컨테이너가 쓰기 가능한 사용자로 설정
        fsGroup: 1001     # /var/lib/mysql 등 볼륨에 대한 그룹 권한
      containers:
        - name: pxc
          env:
            - name: MYSQL_GENERAL_LOG
              value: "1"
            - name: MYSQL_SLOW_LOG
              value: "1"
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

  backup:
    enabled: false
    image: percona/percona-xtradb-cluster-operator:1.11.0

  logCollector:
    enabled: true

  proxysql:
    enabled: true
    size: 2
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
    expose:
      enabled: false
