apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: my-cluster
  namespace: mysql-operator
spec:
  crVersion: 1.9.0
  secretsName: my-cluster-secret
  sslSecretName: my-cluster-ssl
  sslInternalSecretName: my-cluster-ssl-internal

  mysqlVersion: 8.0.32-24.2

  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.26-17.1
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi

  backup:
    enabled: false
    image: percona/percona-xtradb-cluster-operator:1.11.0

  logCollector:
    enabled: true


  expose:
    enabled: true
    type: LoadBalancer
    exposeType: direct