apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: my-cluster
  namespace: mysql-operator
spec:
  crVersion: 1.11.0
  secretsName: my-cluster-secret
  sslSecretName: my-cluster-ssl
  sslInternalSecretName: my-cluster-ssl-internal

  mysqlVersion: 8.0.35-27.1

  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.35-27.1
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
    configurationConfigMap: my-cluster-pxc-config
    resources:
      limits:
        cpu: 1000m
        memory: 1G
      requests:
        cpu: 600m
        memory: 1G

  backup:
    enabled: false
    image: percona/percona-xtradb-cluster-operator:1.11.0

  logCollector:
    enabled: false
    image: percona/percona-xtradb-cluster-operator:1.11.0-logcollector
    

  proxysql:
    enabled: true
    size: 2
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
    expose:
      enabled: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cluster-pxc-config
  namespace: mysql-operator
data:
  my.cnf: |
    [mysqld]    
    default_authentication_plugin=caching_sha2_password
    general_log=1
    log_output=FILE
    general_log_file=/var/lib/mysql/general.log