apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: my-cluster
  namespace: mysql-operator
spec:
  crVersion: 1.11.0
  secretsName: my-cluster-secret
  sslSecretName: my-cluster-ssl
  sslInternalSecretName: my-cluster-ssl-internal

  mysqlVersion: 8.0.35-27.1

  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.35-27.1
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
    configuration: |
      [mysqld]
      wait_timeout = 0
      interactive_timeout = 0
      max_connections = 200
      max_connect_errors = 1000000
      connect_timeout = 0
      net_read_timeout = 0
      net_write_timeout = 0
            
  backup:
    enabled: false
    image: percona/percona-xtradb-cluster-operator:1.11.0

  logCollector:
    enabled: true

  proxysql:
    enabled: true
    size: 2
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    expose:
      enabled: false
    configuration: |
      mysql-connection_max_allowed_packet=67108864
      mysql-max_connections=2000
      mysql-default_max_connections_per_user=100
      mysql-connection_timeout_server=0
      mysql-connection_timeout_client=0
      mysql-connection_timeout_server_max=0
