apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: my-cluster
  namespace: mysql-operator
spec:
  crVersion: 1.11.0
  secretsName: my-cluster-secret
  sslSecretName: my-cluster-ssl
  sslInternalSecretName: my-cluster-ssl-internal

  mysqlVersion: 8.0.35-27.1

  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.35-27.1
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
    extraFlags:
      - "--default-authentication-plugin=caching_sha2_password"
      - "--log_error_services=log_sink_json"
      - "--general-log=1"
      - "--general-log-file=/dev/stdout"  # stdout으로 출력
    resources:
      limits:
        cpu: 1000m
        memory: 1G
      requests:
        cpu: 600m
        memory: 1G

  backup:
    enabled: false
    image: percona/percona-xtradb-cluster-operator:1.11.0

  logCollector:
    enabled: true
    # ✨ 이 라인을 추가하여 logCollector 이미지를 명시적으로 설정하세요.
    image: percona/percona-xtradb-cluster-operator:1.11.0-logcollector

  proxysql:
    enabled: true
    size: 2
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
    expose:
      enabled: false