apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: my-cluster
  namespace: mysql-operator
spec:
  crVersion: 1.11.0
  secretsName: my-cluster-secret
  sslSecretName: my-cluster-ssl
  sslInternalSecretName: my-cluster-ssl-internal

  mysqlVersion: 8.0.35-27.1

  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.35-27.1
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
    configuration: |
      [mysqld]
      # 콘솔 로깅 설정 (stdout으로 출력)
      log_error_verbosity = 3
      log_timestamps = SYSTEM
      
      # 제네럴 로그를 stdout으로 출력
      general_log = ON
      log_output = FILE
      general_log_file = /proc/1/fd/1
      
      # 슬로우 쿼리 로그도 stdout으로 출력
      slow_query_log = ON
      long_query_time = 2
      slow_query_log_file = /proc/1/fd/1
      
      # 에러 로그를 stderr로 출력
      log_error = /proc/1/fd/2
      
      # 인증 설정
      default_authentication_plugin = caching_sha2_password
      
      # 바이너리 로그 설정
      log_bin = mysql-bin
      binlog_format = ROW
      expire_logs_days = 7
      
      # 문자셋 설정
      character_set_server = utf8mb4
      collation_server = utf8mb4_unicode_ci
      
    resources:
      limits:
        cpu: 1000m
        memory: 1G
      requests:
        cpu: 600m
        memory: 1G

  backup:
    enabled: false
    image: percona/percona-xtradb-cluster-operator:1.11.0

  logCollector:
    enabled: false
    image: percona/percona-xtradb-cluster-operator:1.11.0-logcollector
    

  proxysql:
    enabled: true
    size: 2
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
    expose:
      enabled: false
