apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: my-cluster
  namespace: mysql-operator
spec:
  crVersion: 1.11.0
  secretsName: my-cluster-secret
  sslSecretName: my-cluster-ssl
  sslInternalSecretName: my-cluster-ssl-internal

  mysqlVersion: 8.0.35-27.1

  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.35-27.1
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

    podSpec:
      volumes:
        - name: mysql-logs
          emptyDir: {}
        - name: promtail-config
          configMap:
            name: promtail-config
      sidecars:
        - name: promtail
          image: grafana/promtail:2.8.2
          args:
            - -config.file=/etc/promtail/config.yaml
          volumeMounts:
            - name: mysql-logs
              mountPath: /var/log/mysql
              readOnly: true
            - name: promtail-config
              mountPath: /etc/promtail
              readOnly: true

  backup:
    enabled: false
    image: percona/percona-xtradb-cluster-operator:1.11.0

  logCollector:
    enabled: true

  proxysql:
    enabled: true
    size: 2
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
    expose:
      enabled: false
