apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: my-cluster
  namespace: mysql-operator
spec:
  crVersion: 1.11.0
  secretsName: my-cluster-secret
  sslSecretName: my-cluster-ssl
  sslInternalSecretName: my-cluster-ssl-internal

  mysqlVersion: 8.0.35-27.1

  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.35-27.1
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

    sidecars:
    - image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo echo $(date -u) 'test' >> /dev/null; sleep 5; done"]
      name: my-sidecar-1
      volumeMounts:
      - mountPath: /volume1
        name: sidecar-volume-claim
    sidecarPVCs:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: sidecar-volume-claim
      spec:
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce

  backup:
    enabled: false
    image: percona/percona-xtradb-cluster-operator:1.11.0

  logCollector:
    enabled: true

  proxysql:
    enabled: true
    size: 2
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
    expose:
      enabled: false
