apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: my-cluster
  namespace: mysql-operator
spec:
  crVersion: 1.11.0
  secretsName: my-cluster-secret
  sslSecretName: my-cluster-ssl
  sslInternalSecretName: my-cluster-ssl-internal

  mysqlVersion: 8.0.35-27.1

  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.35-27.1
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi

  # ProxySQL 설정 추가 (권장)
  proxysql:
    enabled: true
    size: 2
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

  backup:
    enabled: false
    image: percona/percona-xtradb-cluster-operator:1.11.0

  logCollector:
    enabled: true

  expose:
    enabled: true
    type: LoadBalancer
    exposeType: direct

---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-proxysql-lb
  namespace: mysql-operator
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: proxysql
    app.kubernetes.io/instance: my-cluster
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  loadBalancerSourceRanges:
    - 119.42.188.175/32   # 허용할 외부 IP (CIDR 형식)

