apiVersion: v1
kind: Service
metadata:
  name: my-cluster-proxysql
  namespace: mysql-operator
spec:
  type: LoadBalancer
  loadBalancerIP: 119.42.188.175
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
    - port: 6032
      targetPort: 6032
      protocol: TCP
      name: admin
  selector:
    app.kubernetes.io/component: proxysql
    app.kubernetes.io/instance: my-cluster
    app.kubernetes.io/name: percona-xtradb-cluster
