apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
  namespace: web-service
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  namespace: web-service
subjects:
- kind: ServiceAccount
  name: default               # web-service 네임스페이스의 default SA
  namespace: web-service
roleRef:
  kind: Role
  name: leader-election-role
  apiGroup: rbac.authorization.k8s.io