apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com-cert
  namespace: default
spec:
  secretName: example-com-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  commonName: nkp.neteer.co.kr
  dnsNames:
    - nkp.neteer.co.kr
