apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http
spec:
  acme:
    # Let's Encrypt Staging (테스트용), 실사용 시 prod로 변경
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hskang@neteer.co.kr
    privateKeySecretRef:
      name: letsencrypt-http-private-key
    solvers:
      - http01:
          ingress:
            class: nginx