apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: hskang@neteer.co.kr
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
          ingressTemplate:
            spec:
              rules:
              - http:
                  paths:
                  - path: /.well-known/acme-challenge/
                    pathType: Prefix