apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: default-pool
spec:
  addresses:
  - 119.42.188.175-119.42.188.175  # 여기서 IP 대역을 적절히 조정하세요
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: default-advertisement
spec: {}
